global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: tfl_bikepoint
    static_configs:
      - targets: ["tfl_bikepoint:8000"]

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - scheme: https
      static_configs:
        - targets:
            - "alertmanager_main:9093"
