version: "3.9"

services:
  prometheusmonitor:
    image: prometheusmonitor
    build:
      context: .
      dockerfile: .prometheus_monitor/Dockerfile

  tfl_bikepoint:
    image: tfl_bikepoint
    build:
      context: .
      dockerfile: tfl_bikepoint/Dockerfile
